### DISCUSSION TITLE
Running zenko/cloudserver locally, configured with docker-compose.yml

### DISCUSSION THREAD

**Discussion by zubozrout** [scality/Zenko#1779] [Q&A] [answered]
Hi,
I am trying to get `zenko/cloudserver` docker image work with docker-compose and a Node.js app. So far I've been able to use AWS S3 bucket, localstack and minio, but I've not been successul with cloudserver at all.

The following is basically what I have in my docker-compose.yml file:
```
  cloudserver:
    image: zenko/cloudserver:latest
    ports:
      - "8000:8000"
      - "9990:9990"
      - "9991:9991"
    volumes:
      - s3data:/data
      - s3metadata:/metadata
    restart: unless-stopped
    environment:
      - SCALITY_ACCESS_KEY_ID=test
      - SCALITY_SECRET_ACCESS_KEY=test
      - S3DATAPATH=/data
      - S3METADATAPATH=/metadata
      - REMOTE_MANAGEMENT_DISABLE=1

  jobsystem-node:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - AWS_URL=cloudserver:8000
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=eu-west-1
    depends_on:
      - cloudserver
```

Then the Node.js code is unable to connect to it (failing on the `createBucket()`) with the following code:
```
export const s3 = new AWS.S3({
  accessKeyId: process.env.AWS_ACCESS_KEY_ID,
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  endpoint: process.env.AWS_URL,
  s3ForcePathStyle: true,
  signatureVersion: "v4",
  signatureCache: false
});

const response = await s3.createBucket({
  Bucket: bucketName,
  CreateBucketConfiguration: {
    LocationConstraint: process.env.AWS_REGION
  }
}).promise();
```

and the following error:
```
UnknownEndpoint: Inaccessible host: `cloudserver' at port `8000'. This service may not be available in the `eu-west-1' region.
[...]
originalError: Error: connect ECONNREFUSED 172.22.0.3:8000
[...]
code: 'NetworkingError'
```

I can also see the following issues from the cloudserver docker itself:
```
{"name":"MetadataFileServer","time":1673276638369,"error":"Cannot find module 'ioctl' ... }
{"name":"DataFileStore","time":1673276638556,"error":"Cannot find module 'ioctl' ... }
```

I can access `http://localhost:8000` though, getting an "AccessDenied" xml, so something is running

Is there a way to make this work? Does anyone know how and/or what is the issue?
I wasn't able to find much useful on this topic online sadly.

Ps. This is what I've basically posted a while back: https://github.com/scality/cloudserver/issues/4688 but since then I made no progress on this one and now I landed on the same dead-end spot.

Thank you very much.
Best regards

**Comment by TheDanielz3** [comment, marked as answer]
hey you need disable SSL/TLS for localhost.

**Reply by zubozrout** [reply]
Thank you. Yes, that's a good one!
I completely forgot I actually asked here, but yes, that was my ultimate solution as well.

**Comment by Sieboldianus** [comment]
For anyone, posting my docker-compsose.yml here that I use to add S3 storage to a Grist instance. The critical piece was adding a healthcheck based on node to scality, so grist waits until scality cloudserver is up:
```yaml
  # Scality S3 Server
  scality:
    image: zenko/cloudserver:latest
    container_name: scality_s3
    restart: always
    environment:
      # Disable connection to Zenko Orbit (Cloud Dashboard)
      REMOTE_MANAGEMENT_DISABLE: 1
      # Define credentials
      SCALITY_ACCESS_KEY_ID: ${SCALITY_KEY}
      SCALITY_SECRET_ACCESS_KEY: ${SCALITY_SECRET}
      # Register the docker internal hostname
      ENDPOINT: scality_s3
    volumes:
      - /srv/servicexyz/data/scality:/usr/src/app/localData
      - /srv/servicexyz/data/scality_meta:/usr/src/app/localMetadata
    healthcheck:
      # Use Node.js to check the port
      test: ["CMD", "node", "-e", "const c = require('net').connect(8000, '127.0.0.1', () => process.exit(0)); c.on('error', () => process.exit(1)); c.setTimeout(2000, () => process.exit(1));"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
    # ports:
      # Expose for initial setup
      # - "127.0.0.1:8000:8000"

```

Then add to your main service that uses scality s3:
```yaml
    depends_on:
      scality:
        condition: service_healthy
```
